### ISSUE TITLE
Create a Modal dialog box from the ModalService, and AfterClose will execute it twice

### ISSUE THREAD

**Issue by LingDian2019** [ant-design-blazor/ant-design-blazor#1255]
### Describe the bug

Create a Modal dialog box from the ModalService, and AfterClose will execute it twice

### Steps to reproduce (please include code)
1:https://ant-design-blazor.gitee.io/zh-CN/components/modal
![image](https://user-images.githubusercontent.com/49890738/111257616-6aad8c00-8656-11eb-8fe5-49fef2d1b59d.png)

![image](https://user-images.githubusercontent.com/49890738/111257654-7bf69880-8656-11eb-8adf-625218bb770c.png)

### Further technical details
- AntDesign Nuget Package version 0.6
- Include the output of `dotnet --info`
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version vs

**Comment by zxyao145** [comment]
Thanks, this problem has been found and fixed in my local repository, please wait for the next PR ( Should be this weekend ).

**Comment by zxyao145** [comment]
The PR has been merged to the branch "ant-design-blazor:feature", and so closing this down.

**Comment by JiaChengLuo** [comment]
@zxyao145 Hello, I found that this problem still exists in version 0.7.4😂

**Comment by ElderJames** [comment]
It would release with the 0.8
