### ISSUE TITLE
Table in the simultaneous use of PageSize, HidePagination, OnChange when the page will appear to be stuck in a dead loop

### ISSUE THREAD

**Issue by wangj90** [ant-design-blazor/ant-design-blazor#2904]
### Describe the bug

Table in the simultaneous use of PageSize, HidePagination, OnChange when the page will appear to be stuck in a dead loop

### Steps to reproduce (please include code)

![image](https://user-images.githubusercontent.com/25636510/204071731-804d0442-c528-49df-8a5c-c5f95b19703e.png)

See attachment below

### Further technical details
- AntDesign Nuget Package version
  0.13.0
- Include the output of `dotnet --info`
    .NET SDK:
   Version:   7.0.100
   Commit:    e12b7af219

    运行时环境:
     OS Name:     Windows
     OS Version:  10.0.22621
     OS Platform: Windows
     RID:         win10-x64
     Base Path:   C:\Program Files\dotnet\sdk\7.0.100\
    
    Host:
      Version:      7.0.0
      Architecture: x64
      Commit:       d099f075e4
- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  VS

### Demo
[BlazorApp-empty1.zip](https://github.com/ant-design-blazor/ant-design-blazor/files/10095626/BlazorApp-empty1.zip)
It contains git versioning, with 3 commits, the last of which is the commit that reproduces the bug.
The example uses the one in the documentation: <https://antblazor.com/zh-CN/components/table#components-table-demo-ajax>

**Comment by tht245806497** [comment]
I also found a small problem about the HidePageination feature. 
When using the OnInitializedAsync to load data asynchronously,  an explicit call StateHasChanged is required. Otherwise, no data will be displayed.

**Comment by tht245806497** [comment]
It seems that PageSize is not automatically updated. 
If explicitly specify "PageSize=@dsList.Count“, StateHasChanged is not required.

**Comment by ldsenow** [comment]
Same here. Hopefully it is fixed soon.

**Comment by ElderJames** [comment]
@ldsenow I have fixed it in #2905

**Comment by wangj90** [comment]
This problem has not been solved yet.
when I upgraded to AntDesign 0.13.1, the above demo still did not solve the stuck problem when I ran it.
