### ISSUE TITLE
Gray background after 0.14.0 update

### ISSUE THREAD

**Issue by mrjohnr** [ant-design-blazor/ant-design-blazor#3046]
I've updated to v.14.0 but all my app goes with gray background, it could be because of new theme service,I've not found much info into docs but  to add   id="antcss"  on ` <link href="_content/AntDesign/css/ant-design-blazor.css" rel="stylesheet" id="antcss" />`
reverting to v.13.3 looks fine, I think default behavior that should be

**Comment by ElderJames** [comment]
Thanks for contacting us @mrjohnr , could you provide a demo?

**Comment by mrjohnr** [comment]
Hi
Could not reproduce it with a new project, I've fixed adding in styles.css
```
#app {
    background-color: white !important;
}
```
thanks

**Comment by true-perfect-code** [comment]
The background of the drawer is not set correctly when the drawer is invisible:

![image](https://user-images.githubusercontent.com/45635963/215805104-85998f54-dd00-4323-a939-ffe8e4492394.png)

![image](https://user-images.githubusercontent.com/45635963/215805285-54165942-3e11-4388-ba6d-a5a537b6c918.png)

If you go back to the 13.3. version, the problem unfortunately also exists.

**Comment by ElderJames** [comment]
Hello @mrjohnr , @true-perfect-code , this issue maybe the same to #3045 and have been fixed.

**Comment by true-perfect-code** [comment]
@ElderJames 

I also think it's the same problem.

Is a preview version available so that we can install it?

Thanks

**Comment by ElderJames** [comment]
Please follow the guide

https://antblazor.com/en-US/docs/nightly-build

**Comment by true-perfect-code** [comment]
Thank you @ElderJames 

I may wait for the next version. When is it actually scheduled for release?

**Comment by ElderJames** [comment]
@true-perfect-code @mrjohnr  We have released 0.14.1, please try.

**Comment by true-perfect-code** [comment]
I have installed 14.1, unfortunately the problem still exists.

![image](https://user-images.githubusercontent.com/45635963/216058315-bc9ed2d9-950d-4c32-a83b-65bc31c1b4be.png)

![image](https://user-images.githubusercontent.com/45635963/216058666-ae682479-9a74-4752-b328-d66418a6223d.png)

**Comment by mrjohnr** [comment]
tried v0.14.1 without css fix,the same problem: gray background

**Comment by ldsenow** [comment]
> tried v0.14.1 without css fix,the same problem: gray background

Me too.

**Comment by CyberryCJ** [comment]
I tried the new version. I've got the same result.
![image](https://user-images.githubusercontent.com/36914098/216208775-29d2485a-d707-4ae5-8363-ae47e8c1d398.png)

**Comment by ElderJames** [comment]
hello @mrjohnr  @ldsenow @CyberryCJ , could you please provide a demo?

**Comment by zxyao145** [comment]
Hi all, I have found the reason. The dom class is changed in react, but the blazer is not synchronized.

**Comment by mrjohnr** [comment]
problem seem fixed in v0.14.2
thanks

**Comment by true-perfect-code** [comment]
Thanks, it works :)
