### ISSUE TITLE
using GenerateColumns and general columns at the same time will course header and cell not align properly

### ISSUE THREAD

**Issue by lujie19930803** [ant-design-blazor/ant-design-blazor#4177]
### Describe the bug

table has ScrollX and ScrollY at the same time will course header and cell not align properly

### Steps to reproduce (please include code)
i have a table with proerty ScrollX and ScrollY at the same time. this course  header and cell not align properly. but when i only use ScrollX. the table work correctly.

### Exceptions 
![image](https://github.com/user-attachments/assets/1c470d8f-d84f-42a0-83d2-06fc8107c3d7)

![image](https://github.com/user-attachments/assets/87cdc4e2-0878-4d7a-a327-85dee7518441)

**Comment by lujie19930803** [comment]
@ElderJames

**Comment by ElderJames** [comment]
It seems works well
![image](https://github.com/user-attachments/assets/4ae5cb4a-242e-4cdb-9b09-1b619b97cfbc)

**Comment by lujie19930803** [comment]
sorry this happed when i use GenerateColumns. Below is my simple code.

```
<Table TItem="Data" DataSource="@data" ScrollBarWidth="7px" ScrollX="1000" AutoHeight>
      <GenerateColumns Range="1.." Definitions=definitions />
      <ActionColumn Title="Action">
          <Space Size=@("middle")>
              <SpaceItem>
                  <a>aaa</a>
              </SpaceItem>
              <SpaceItem>
                  <a>Delete</a>
              </SpaceItem>
          </Space>
      </ActionColumn>
</Table>
```

```
@code {
    Data[] data = new Data[]
        {
        new()
        {
            Key = "1",
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
            Tags = new[] {"nice", "developer"},
            IdCard = "",
            Key1 = "1",
            Name1 = "John Brown",
            Age1 = 32,
            Address1 = "New York No. 1 Lake Park",
            Tags1 = new[] {"nice", "developer"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "2",
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
            Tags = new[] { "loser"},
            IdCard = "",
            Key1 = "2",
            Name1 = "Jim Green",
            Age1 = 42,
            Address1 = "London No. 1 Lake Park",
            Tags1 = new[] { "loser"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "3",
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
            Tags = new[] { "cool", "teacher" },
            IdCard = "",
            Key1 = "3",
            Name1 = "Joe Black",
            Age1 = 32,
            Address1 = "Sidney No. 1 Lake Park",
            Tags1 = new[] { "cool", "teacher" },
            IdCard1 = "",
            Key2 = "3",
            Name2 = "Joe Black",
            Age2 = 32,
            Address2 = "Sidney No. 1 Lake Park",
            Tags2 = new[] { "cool", "teacher" },
            IdCard2 = ""
        }
        };
    public class Data
    {
        [DisplayName("Key")]
        public string Key { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Tags")]
        public string[] Tags { get; set; }

        [DisplayName("IdCard")]
        public string IdCard { get; set; }

        [DisplayName("Key1")]
        public string Key1 { get; set; }

        [DisplayName("Name1")]
        public string Name1 { get; set; }

        [DisplayName("Age1")]
        public int Age1 { get; set; }

        [DisplayName("Address1")]
        public string Address1 { get; set; }

        [DisplayName("Tags1")]
        public string[] Tags1 { get; set; }

        [DisplayName("IdCard1")]
        public string IdCard1 { get; set; }

        [DisplayName("Key2")]
        public string Key2 { get; set; }

        [DisplayName("Name2")]
        public string Name2 { get; set; }

        [DisplayName("Age2")]
        public int Age2 { get; set; }

        [DisplayName("Address2")]
        public string Address2 { get; set; }

        [DisplayName("Tags2")]
        public string[] Tags2 { get; set; }

        [DisplayName("IdCard2")]
        public string IdCard2 { get; set; }
    }

    /// <summary>
    /// An Action to defined each column
    /// </summary>
    /// <param name="propertyName">The name of the property binding the column. </param>
    /// <param name="column">The column instance, you need to explicitly cast to a concrete Column type. </param>
    void definitions(string propertyName, IFieldColumn column)
    {
        if (propertyName == "Tags")
        {
            var tagCol = ((Column<string[]>)column);

            tagCol.CellRender = cellData =>
    @<span>
        @foreach (var tag in cellData.FieldValue)
    {
    var color = tag.Length > 5 ? "geekblue" : "green";
    if (tag == "loser")
    {
    color = "volcano";
    }
        <Tag Color="@color">@tag</Tag>
    }
    </span>
    ;

            return;
        }

        column.Sortable = false;
        column.Filterable = false;
    }
}
```
the only difference with official demo is i use ScrollX="1000" and AutoHeight @ElderJames 
![image](https://github.com/user-attachments/assets/3470b226-9c4f-4fff-a18a-91f4b2213995)

**Comment by shuangbaojun** [comment]
I've had the same problem.  Static columns do not have problems, dynamic columns will have the same problems (set scroll.x, scroll.y values at the same time)  @ElderJames

**Comment by Kand-wang** [comment]
I've had the same problem.
<img width="1045" alt="微信图片_20240912093103" src="https://github.com/user-attachments/assets/21cde651-148b-49cd-9c19-22787056b6d8">
<img width="980" alt="微信图片_20240912093236" src="https://github.com/user-attachments/assets/13b3cdff-7ff7-476c-95c6-67e4c4716e8b">

**Comment by ElderJames** [comment]
Thanks for contacting us @shuangbaojun , @Kand-wang , @lujie19930803 , this issue have been fixed in #4195

**Comment by lujie19930803** [comment]
![image](https://github.com/user-attachments/assets/bea35aa6-0fc8-4ab1-8363-a3a6cd6b9383)
@ElderJames is this problem fixed in 1.0.0-rc.1? i still have this problem after i upgrade to 1.0.0-rc.1

**Comment by ElderJames** [comment]
Hello @lujie19930803 , could you please post your code here?

**Comment by lujie19930803** [comment]
`<Table TItem="Data" DataSource="@data" ScrollBarWidth="7px" ScrollX="1000" AutoHeight>
      <GenerateColumns Range="1.." Definitions=definitions />
      <ActionColumn Title="Action">
          <Space Size=@("middle")>
              <SpaceItem>
                  <a>aaa</a>
              </SpaceItem>
              <SpaceItem>
                  <a>Delete</a>
              </SpaceItem>
          </Space>
      </ActionColumn>
</Table>`

`@code {
    Data[] data = new Data[]
        {
        new()
        {
            Key = "1",
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
            Tags = new[] {"nice", "developer"},
            IdCard = "",
            Key1 = "1",
            Name1 = "John Brown",
            Age1 = 32,
            Address1 = "New York No. 1 Lake Park",
            Tags1 = new[] {"nice", "developer"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "2",
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
            Tags = new[] { "loser"},
            IdCard = "",
            Key1 = "2",
            Name1 = "Jim Green",
            Age1 = 42,
            Address1 = "London No. 1 Lake Park",
            Tags1 = new[] { "loser"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "3",
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
            Tags = new[] { "cool", "teacher" },
            IdCard = "",
            Key1 = "3",
            Name1 = "Joe Black",
            Age1 = 32,
            Address1 = "Sidney No. 1 Lake Park",
            Tags1 = new[] { "cool", "teacher" },
            IdCard1 = "",
            Key2 = "3",
            Name2 = "Joe Black",
            Age2 = 32,
            Address2 = "Sidney No. 1 Lake Park",
            Tags2 = new[] { "cool", "teacher" },
            IdCard2 = ""
        }
        };
    public class Data
    {
        [DisplayName("Key")]
        public string Key { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Tags")]
        public string[] Tags { get; set; }

        [DisplayName("IdCard")]
        public string IdCard { get; set; }

        [DisplayName("Key1")]
        public string Key1 { get; set; }

        [DisplayName("Name1")]
        public string Name1 { get; set; }

        [DisplayName("Age1")]
        public int Age1 { get; set; }

        [DisplayName("Address1")]
        public string Address1 { get; set; }

        [DisplayName("Tags1")]
        public string[] Tags1 { get; set; }

        [DisplayName("IdCard1")]
        public string IdCard1 { get; set; }

        [DisplayName("Key2")]
        public string Key2 { get; set; }

        [DisplayName("Name2")]
        public string Name2 { get; set; }

        [DisplayName("Age2")]
        public int Age2 { get; set; }

        [DisplayName("Address2")]
        public string Address2 { get; set; }

        [DisplayName("Tags2")]
        public string[] Tags2 { get; set; }

        [DisplayName("IdCard2")]
        public string IdCard2 { get; set; }
    }

    /// <summary>
    /// An Action to defined each column
    /// </summary>
    /// <param name="propertyName">The name of the property binding the column. </param>
    /// <param name="column">The column instance, you need to explicitly cast to a concrete Column type. </param>
    void definitions(string propertyName, IFieldColumn column)
    {
        if (propertyName == "Tags")
        {
            var tagCol = ((Column<string[]>)column);

            tagCol.CellRender = cellData =>
    @<span>
        @foreach (var tag in cellData.FieldValue)
    {
    var color = tag.Length > 5 ? "geekblue" : "green";
    if (tag == "loser")
    {
    color = "volcano";
    }
        <Tag Color="@color">@tag</Tag>
    }
    </span>
    ;

            return;
        }

        column.Sortable = false;
        column.Filterable = false;
    }
}`

@ElderJames

**Comment by lujie19930803** [comment]
```
<Table TItem="Data" DataSource="@data" ScrollBarWidth="7px" ScrollX="1000" AutoHeight>
      <GenerateColumns Range="1.." Definitions=definitions />
      <ActionColumn Title="Action">
          <Space Size=@("middle")>
              <SpaceItem>
                  <a>aaa</a>
              </SpaceItem>
              <SpaceItem>
                  <a>Delete</a>
              </SpaceItem>
          </Space>
      </ActionColumn>
</Table>
```

```
@code {
    Data[] data = new Data[]
        {
        new()
        {
            Key = "1",
            Name = "John Brown",
            Age = 32,
            Address = "New York No. 1 Lake Park",
            Tags = new[] {"nice", "developer"},
            IdCard = "",
            Key1 = "1",
            Name1 = "John Brown",
            Age1 = 32,
            Address1 = "New York No. 1 Lake Park",
            Tags1 = new[] {"nice", "developer"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "2",
            Name = "Jim Green",
            Age = 42,
            Address = "London No. 1 Lake Park",
            Tags = new[] { "loser"},
            IdCard = "",
            Key1 = "2",
            Name1 = "Jim Green",
            Age1 = 42,
            Address1 = "London No. 1 Lake Park",
            Tags1 = new[] { "loser"},
            IdCard1 = "",
            Key2 = "2",
            Name2 = "Jim Green",
            Age2 = 42,
            Address2 = "London No. 1 Lake Park",
            Tags2 = new[] { "loser"},
            IdCard2 = ""
        },
        new()
        {
            Key = "3",
            Name = "Joe Black",
            Age = 32,
            Address = "Sidney No. 1 Lake Park",
            Tags = new[] { "cool", "teacher" },
            IdCard = "",
            Key1 = "3",
            Name1 = "Joe Black",
            Age1 = 32,
            Address1 = "Sidney No. 1 Lake Park",
            Tags1 = new[] { "cool", "teacher" },
            IdCard1 = "",
            Key2 = "3",
            Name2 = "Joe Black",
            Age2 = 32,
            Address2 = "Sidney No. 1 Lake Park",
            Tags2 = new[] { "cool", "teacher" },
            IdCard2 = ""
        }
        };
    public class Data
    {
        [DisplayName("Key")]
        public string Key { get; set; }

        [DisplayName("Name")]
        public string Name { get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }

        [DisplayName("Address")]
        public string Address { get; set; }

        [DisplayName("Tags")]
        public string[] Tags { get; set; }

        [DisplayName("IdCard")]
        public string IdCard { get; set; }

        [DisplayName("Key1")]
        public string Key1 { get; set; }

        [DisplayName("Name1")]
        public string Name1 { get; set; }

        [DisplayName("Age1")]
        public int Age1 { get; set; }

        [DisplayName("Address1")]
        public string Address1 { get; set; }

        [DisplayName("Tags1")]
        public string[] Tags1 { get; set; }

        [DisplayName("IdCard1")]
        public string IdCard1 { get; set; }

        [DisplayName("Key2")]
        public string Key2 { get; set; }

        [DisplayName("Name2")]
        public string Name2 { get; set; }

        [DisplayName("Age2")]
        public int Age2 { get; set; }

        [DisplayName("Address2")]
        public string Address2 { get; set; }

        [DisplayName("Tags2")]
        public string[] Tags2 { get; set; }

        [DisplayName("IdCard2")]
        public string IdCard2 { get; set; }
    }

    /// <summary>
    /// An Action to defined each column
    /// </summary>
    /// <param name="propertyName">The name of the property binding the column. </param>
    /// <param name="column">The column instance, you need to explicitly cast to a concrete Column type. </param>
    void definitions(string propertyName, IFieldColumn column)
    {
        if (propertyName == "Tags")
        {
            var tagCol = ((Column<string[]>)column);

            tagCol.CellRender = cellData =>
    @<span>
        @foreach (var tag in cellData.FieldValue)
    {
    var color = tag.Length > 5 ? "geekblue" : "green";
    if (tag == "loser")
    {
    color = "volcano";
    }
        <Tag Color="@color">@tag</Tag>
    }
    </span>
    ;

            return;
        }

        column.Sortable = false;
        column.Filterable = false;
    }
}
```
@ElderJames Please help me take a look.

**Comment by lujie19930803** [comment]
@ElderJames is this problem fixed?

**Comment by ElderJames** [comment]
@lujie19930803 Sorry, not yet. You can add the action column through GenerateColumns.

**Comment by ElderJames** [comment]
duplicated #3697

**Comment by ElderJames** [comment]
Please try ColIndex.
